import type { Metadata } from 'next';
import { locales, defaultLocale, type Locale } from '@/lib/i18n';
import { siteConfig } from '@/lib/constants';

export function generateStaticParams() {
  return locales.map(locale => ({ locale }));
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const loc = (locales.includes(locale as any) ? locale : defaultLocale) as Locale;
  return {
    title: loc === 'en' ? 'Disclaimer' : loc === 'zh-TW' ? '免責聲明' : loc === 'es' ? 'Aviso Legal' : '免責事項',
    alternates: { canonical: `/${loc}/disclaimer` },
  };
}

export default async function DisclaimerPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const loc = (locales.includes(locale as any) ? locale : defaultLocale) as Locale;

  const content = loc === 'en' ? [
    { h: 'Disclaimer', p: 'The information and tools provided on this website are for general informational purposes only.' },
    { h: 'No Warranty', p: 'QR codes generated by this tool are provided without any warranty. We do not guarantee that generated QR codes will be scannable by all devices or in all conditions. Always test your QR codes before public deployment.' },
    { h: 'Not Professional Advice', p: 'Content on this website, including blog posts and guides, is for educational purposes only and does not constitute professional advice.' },
    { h: 'User Responsibility', p: 'Users are solely responsible for the content encoded in QR codes generated using this tool. This includes ensuring that linked URLs are safe, accurate, and comply with applicable laws.' },
    { h: 'Third-Party Links', p: 'This website may contain links to third-party websites. We are not responsible for the content or practices of these external sites.' },
    { h: 'Trademark Notice', p: '"QR Code" is a registered trademark of Denso Wave Incorporated. This website is not affiliated with or endorsed by Denso Wave.' },
  ] : loc === 'zh-TW' ? [
    { h: '免責聲明', p: '本網站提供的資訊和工具僅供一般參考之用。' },
    { h: '無保證', p: '本工具產生的 QR Code 不附帶任何保證。我們不保證產生的 QR Code 能在所有裝置或所有條件下掃描。' },
    { h: '非專業建議', p: '本網站的內容僅供教育目的，不構成專業建議。' },
    { h: '使用者責任', p: '使用者需對使用本工具產生的 QR Code 中編碼的內容負全部責任。' },
    { h: '第三方連結', p: '本網站可能包含第三方網站的連結。我們不對這些外部網站的內容或做法負責。' },
    { h: '商標聲明', p: '"QR Code" 是 Denso Wave Incorporated 的註冊商標。本網站不隸屬於 Denso Wave。' },
  ] : loc === 'es' ? [
    { h: 'Aviso Legal', p: 'La información y las herramientas de este sitio web son solo para fines informativos generales.' },
    { h: 'Sin Garantía', p: 'Los códigos QR generados por esta herramienta se proporcionan sin garantía.' },
    { h: 'No es Consejo Profesional', p: 'El contenido de este sitio es solo para fines educativos.' },
    { h: 'Responsabilidad del Usuario', p: 'Los usuarios son los únicos responsables del contenido codificado en los códigos QR.' },
    { h: 'Enlaces de Terceros', p: 'Este sitio puede contener enlaces a sitios web de terceros.' },
    { h: 'Aviso de Marca Registrada', p: '"QR Code" es una marca registrada de Denso Wave Incorporated.' },
  ] : [
    { h: '免責事項', p: '本ウェブサイトの情報およびツールは、一般的な情報提供のみを目的としています。' },
    { h: '保証なし', p: '本ツールで生成されたQRコードは、いかなる保証もなく提供されます。' },
    { h: '専門的な助言ではない', p: '本ウェブサイトのコンテンツは教育目的のみです。' },
    { h: 'ユーザーの責任', p: 'ユーザーは、生成されたQRコードにエンコードされたコンテンツに単独で責任を負います。' },
    { h: 'サードパーティリンク', p: '当サイトにはサードパーティのウェブサイトへのリンクが含まれる場合があります。' },
    { h: '商標表示', p: '「QR Code」はデンソーウェーブ株式会社の登録商標です。' },
  ];

  return (
    <>
      <div className="mx-auto max-w-3xl px-4 py-12">
        {content.map((s, i) => (
          <div key={i} className="mb-6">
            <h2 className="text-lg font-bold text-slate-900">{s.h}</h2>
            <p className="mt-1 text-sm text-slate-600 leading-relaxed">{s.p}</p>
          </div>
        ))}
        <p className="mt-8 text-xs text-slate-400">Last updated: 2026-06-27</p>
      </div>
    </>
  );
}
